name: Heroku deployment

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build maven
        run: mvn -B package --file pom.xml

      - name: Sonarcloud Scann
        uses: sonarsource/sonarcloud-github-action@v1.3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy on heroku
        uses: AkhileshNS/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar